SURFACES = ['D', 'T']
RACE_TYPES = ['SPI', 'ALW', 'MDN', 'DBY', 'DTR', 'STK']
COURSE_TYPES = ['D', 'M']
TRACK_CONDITIONS = ['FT', 'GD']
WEATHERS = ['C', 'L']
TRACK_SEALEDS = ['Y', 'N']
SEXES = ['G', 'M', 'F', 'C', 'H']

# MEAN DAYS AFTER RACE
# BASE_MEAN * RATIO = 1/LAMBDA for exponential distribution
BASE_MEAN = 33.558088
DNF_RATIO = 1.708373
VET_SCRATCH_RATIO = 1.353912
BADLY_BEATEN_RATIO = 1.395314
BREAKDOWN_RATIO = 2.527195

TARGET = 'target'